#!/bin/sh
#
# http://github.com/mitchweaver/suckless
#
# wrapper for suckless simple terminal
#
# ensures even terminal size across different machines
#

nohup st -c 'Simple Terminal' -t 'Simple Terminal' "$@" >/dev/null 2>&1 &
