.TH BLIND-CAT-COLS 1 blind
.SH NAME
blind-cat-cols - Place videos side by side
.SH SYNOPSIS
.B blind-cat-cols
.IR stream \ ...
.SH DESCRIPTION
.B blind-cat-cols
reads all specified video
.IR stream s
and writes them side by side, with
the first video to the left and the
last video at the right, to stdout.
.SH SEE ALSO
.BR blind (7),
.BR blind-split-cols (1),
.BR blind-concat (1),
.BR blind-interleave (1),
.BR blind-cat-rows (1),
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
