.TH BLIND-FLOP 1 blind
.SH NAME
blind-flop - Mirror a video horizontally
.SH SYNOPSIS
.B blind-flop
.SH DESCRIPTION
.B blind-flop
reads a video from stdin and prints it, mirrored
horizontally, to stdout.
.SH REQUIREMENTS
.B blind-flop
requires enough free memory to load two frame rows into memory.
A frame row requires 32 bytes per pixel it contains, that is,
32 bytes times the width of the video in pixel.
.SH SEE ALSO
.BR blind (7),
.BR blind-flip (1),
.BR blind-transpose (1),
.BR blind-rotate-90 (1),
.BR blind-rotate-180 (1),
.BR blind-rotate-270 (1)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
