.TH BLIND-FROM-PORTABLE 1 blind
.SH NAME
blind-from-portable - Convert a video from a portable format to a processable format
.SH SYNOPSIS
.B blind-from-portable
[-s]
.SH DESCRIPTION
.B blind-from-portable
converts a video from a portable format to a processable format.
.SH OPTIONS
.B -s
Do not convert single-precision floating-points number
from binary32, and double-precision floating-points number
from binary64, to local encoding.
.SH SEE ALSO
.BR blind (7),
.BR blind-to-portable (1),
.BR blind-from-text (1)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
