.TH BLIND-SET-SATURATION 1 blind
.SH NAME
blind-set-saturation - Multiply the saturation of a video
.SH SYNOPSIS
.B blind-set-saturation
[-w]
.I saturation-stream
.SH DESCRIPTION
.B blind-set-saturation
reads a video from stdin and a mask video from
.IR saturation-stream .
The video is printed to stdout, with the saturation
of each pixel multiplied by the product of the
luminosity and the alpha value of the corresponding
pixel and frame in the mask video.
.P
If stdin is longer than
.IR saturation-stream ,
the remainder of stdin is printed without any changes.
If stdin is shorter than
.IR saturation-stream ,
the remainder of
.I saturation-stream
is ignored but may be partially read.
.SH OPTIONS
.TP
.B -w
Instead of using CIE Standard Illuminant D65 as the
whitepoint, use the X and Z from each pixel in
.I saturation-stream
for the whitepoint.
.SH SEE ALSO
.BR blind (7),
.BR blind-single-colour (1),
.BR blind-arithm (1),
.BR blind-set-alpha (1),
.BR blind-set-luma (1),
.BR blind-invert-luma (1)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
