.TH BLIND-GET-COLOURS 1 blind
.SH NAME
blind-get-colours - Get a frame with all colours from a video
.SH SYNOPSIS
.B blind-get-colours
.SH DESCRIPTION
.B blind-get-colours
reads a video from stdin and prints a single-frame
video to stdout contain all colours from the video.
.SH SEE ALSO
.BR blind (7),
.BR blind-apply-palette (1),
.BR blind-repeat-tessellation (1)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
