.TH BLIND-VECTOR-PROJECTION 1 blind
.SH NAME
blind-vector-projection - Calculate the projection or rejection of colours in a video
.SH SYNOPSIS
.B blind-vector-projection
[-r | -s]
.I plane-stream
.SH DESCRIPTION
.B blind-vector-projection
reads a video from stdin and a video from
.IR plane-stream ,
and calculates the projection of the colours from
stdin onto the colours from
.I plane-stream
and prints the resulting video to stdout.
.P
If stdin is longer than
.IR plane-stream ,
the remainder of stdin is printed without any changes.
If stdin is shorter than
.IR plane-stream ,
the remainder of
.I plane-stream
is ignored but may be partially read.
.SH OPTIONS
.TP
.B -r
Calculate the vector rejection instead of the vector projection.
.TP
.B -s
Calculate the scalar projection instead of the vector projection.
The scalar projection is stored in all four channels.
.SH SEE ALSO
.BR blind (7),
.BR blind-arithm (1),
.BR blind-norm (1),
.BR blind-dot-product (1),
.BR blind-cross-product (1),
.BR blind-quaternion-product (1)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
