.TH BLIND-DISPERSE 1 blind
.SH NAME
blind-disperse - Framewise split a video into multiple videos
.SH SYNOPSIS
.B blind-disperse
.RI ( file
.IR frames )\ ...
.SH DESCRIPTION
.B blind-disperse
reads a video from stdin and splits into multiple videos.
Starting from the first frame in stdin, it writes a video
to the first specified
.I file
until the first specified number of
.I frames
have been written.
.B blind-disperse
then proceeds to do to the same for the next pair of
.I file
and
.I frames
until, and in including, the last pair. This process
is repeated until the last frame in stdin has been read.
.SH RATIONALE
This is useful processing a video on multiple computers.
.SH SEE ALSO
.BR blind (7),
.BR blind-interleave (1),
.BR blind-cut (1),
.BR blind-split (1),
.BR blind-split-cols (1),
.BR blind-split-rows (1),
.BR blind-skip-pattern (1)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
