.TH BLIND-CAT-ROWS 1 blind
.SH NAME
blind-cat-rows - Stack videos vertically
.SH SYNOPSIS
.B blind-cat-rows
.IR stream \ ...
.SH DESCRIPTION
.B blind-cat-rows
reads all specified video
.IR stream s
and writes them vertically stacked, with
the first video at the top and the last
video at the bottom, to stdout.
.SH SEE ALSO
.BR blind (7),
.BR blind-split-rows (1),
.BR blind-concat (1),
.BR blind-interleave (1),
.BR blind-cat-cols (1),
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
