BIN =\
	blind-affine-colour\
	blind-apply-kernel\
	blind-apply-palette\
	blind-arithm\
	blind-cat-cols\
	blind-cat-rows\
	blind-chroma-key\
	blind-colour-ciexyz\
	blind-colour-matrix\
	blind-colour-srgb\
	blind-compress\
	blind-concat\
	blind-cone-gradient\
	blind-convert\
	blind-coordinate-field\
	blind-crop\
	blind-cross-product\
	blind-cut\
	blind-decompress\
	blind-disperse\
	blind-dissolve\
	blind-dot-product\
	blind-double-sine-wave\
	blind-dual-key\
	blind-extend\
	blind-extract-alpha\
	blind-find-rectangle\
	blind-flip\
	blind-flop\
	blind-from-image\
	blind-from-named\
	blind-from-portable\
	blind-from-text\
	blind-from-video\
	blind-gauss-blur\
	blind-get-colours\
	blind-hexagon-tessellation\
	blind-interleave\
	blind-invert-luma\
	blind-invert-matrix\
	blind-kernel\
	blind-linear-gradient\
	blind-make-kernel\
	blind-matrix-orthoproject\
	blind-matrix-reflect\
	blind-matrix-rotate\
	blind-matrix-scale\
	blind-matrix-shear\
	blind-matrix-translate\
	blind-matrix-transpose\
	blind-mean\
	blind-mosaic\
	blind-mosaic-corners\
	blind-mosaic-edges\
	blind-multiply-matrices\
	blind-next-frame\
	blind-norm\
	blind-peek-head\
	blind-premultiply\
	blind-quaternion-product\
	blind-radial-gradient\
	blind-read-head\
	blind-rectangle-tessellation\
	blind-repeat\
	blind-repeat-tessellation\
	blind-reverse\
	blind-rewrite-head\
	blind-round-wave\
	blind-sawtooth-wave\
	blind-set-alpha\
	blind-set-luma\
	blind-set-saturation\
	blind-single-colour\
	blind-sinc-wave\
	blind-sine-wave\
	blind-skip-pattern\
	blind-spatial-arithm\
	blind-spatial-mean\
	blind-spectrum\
	blind-spiral-gradient\
	blind-split\
	blind-split-chans\
	blind-split-cols\
	blind-split-rows\
	blind-square-gradient\
	blind-stack\
	blind-tee\
	blind-temporal-arithm\
	blind-temporal-mean\
	blind-time-blur\
	blind-to-image\
	blind-to-named\
	blind-to-portable\
	blind-to-text\
	blind-to-video\
	blind-transition\
	blind-translate\
	blind-transpose\
	blind-triangle-tessellation\
	blind-triangular-wave\
	blind-unpremultiply\
	blind-vector-projection\
	blind-write-head
