.Dd 2017-07-11
.Dt QUARK 1
.Sh NAME
.Nm quark
.Nd simple web server
.Sh SYNOPSIS
.Nm
.Op Fl l | L
.Op Fl v | V
.Oo
.Oo
.Op Fl h Ar host
.Op Fl p Ar port
.Oc
|
.Op Fl U Ar sockfile
.Oc
.Op Fl d Ar dir
.Op Fl u Ar user
.Op Fl g Ar group
.Sh DESCRIPTION
.Nm
is a simple HTTP GET only web server that can be multiplexed using
UNIX-domain sockets.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d Ar dir
Serve
.Ar dir
after chrooting into it.
.It Fl l
Disable directory listing.
.It Fl L
Enable directory listing.
.It Fl g Ar group
Set group ID to the ID of
.Ar group
when dropping privileges.
.It Fl h Ar host
Use
.Ar host
as the server hostname.
.It Fl p Ar port
Listen on port
.Ar port
for incoming connections.
.It Fl u Ar user
Set user ID to the ID of
.Ar user
when dropping privileges.
.It Fl U Ar sockfile
Create the UNIX-domain socket file
.Ar sockfile
and listen on it for incoming connections.
The file will be cleaned up at exit.
.It Fl v
Disable virtual hosts.
.It Fl V
Enable virtual hosts.
.El
.Sh CUSTOMIZATION
.Nm
can be customized by creating a custom config.h from config.def.h and
(re)compiling the source code. This keeps it fast, secure and simple.
